language: c
sudo: false

os:
    - linux
    - osx

matrix:
    allow_failures:
        - os: osx

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        scons p=linux t=release b=64
    fi
    
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        scons p=osx t=release b=64
    fi
